version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: pubapp-postgres
    environment:
      POSTGRES_DB: pubapp
      POSTGRES_USER: pubapp
      POSTGRES_PASSWORD: pubapp123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pubapp-network

  minio:
    image: minio/minio:latest
    container_name: pubapp-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - pubapp-network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: pubapp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pubapp-network

volumes:
  postgres_data:
  minio_data:
  redis_data:

networks:
  pubapp-network:
    driver: bridge
